package database

import (
	"context"
	"fmt"
	"testing"
	"time"
	scCsv "ui-backend-for-omotebako-site-controller/app/csv"
	"ui-backend-for-omotebako-site-controller/config"

	"github.com/golang/glog"
)

func TestAddReservationInfoToDB(t *testing.T) {
	SampleReservation := scCsv.ReservationData{
		Notice:                             "",
		SalesAgentCode:                     "",
		SalesAgentName:                     "",
		SalesAgentShopName:                 "",
		SalesAgentShopCode:                 0,
		SalesAgentContactPerson:            "",
		SalesAgentContactEmail:             "",
		SalesAgentContactPhoneNumber:       "",
		SalesAgentContactFax:               "",
		SalesAgentPlace:                    "",
		ReservatioinNumber:                 "",
		ReservatioinDate:                   "",
		NotificationNumber:                 0,
		NameKana:                           "",
		Name:                               "",
		StayDateFrom:                       "",
		CheckInTime:                        "",
		StayDateTo:                         "",
		StayDays:                           0,
		Transportation:                     "",
		PassengerCategory:                  "",
		NumberOfRooms:                      0,
		NumberOfGuests:                     0,
		NumberOfGuestsMale:                 0,
		NumberOfGuestsFemale:               0,
		NumberOfGuestsChildA:               0,
		NumberOfGuestsChildB:               0,
		NumberOfGuestsChildC:               0,
		NumberOfGuestsChildD:               0,
		NumberOfGuide:                      0,
		ParticipationForm:                  "",
		ProductName:                        "",
		ProductCode:                        "",
		StayCondition:                      "",
		PricePerUnit:                       "",
		PriceType:                          "",
		TotalPrice:                         0,
		TotalPriceOther:                    0,
		PhoneNumber:                        "",
		Email:                              "",
		PostalCode:                         "",
		HomeAddress:                        "",
		NumberOfGuestsAdult:                0,
		ReservationHolder:                  "",
		ReservationHolderKana:              "",
		ReservationHolderPhoneNumber:       "",
		ReservationHolderEmail:             "",
		ReservationHolderPostalCode:        "",
		ReservationHolderHomeAddress:       "",
		ReservationHolderCompanyName:       "",
		ReservationHolderCompanyDepartment: "",
		ReservationHolderMembershipNumber:  "",
		PointsDiscount:                     0,
		PointsAwarded:                      0,
		PointsAllocated:                    0,
		PaymentMethodName:                  "",
		UseOfDay1:                          0,
		RoomType1:                          "",
		NumberOfRoom1:                      0,
		RoomPrice1:                         0,
		PriceOfMale1:                       0,
		PriceOfFemale1:                     0,
		PriceOfChildA1:                     0,
		PriceOfChildB1:                     0,
		PriceOfChildC1:                     0,
		PriceOfChildD1:                     0,
		UseOfDay2:                          0,
		RoomType2:                          "",
		NumberOfRoom2:                      0,
		RoomPrice2:                         0,
		PriceOfMale2:                       0,
		PriceOfFemale2:                     0,
		PriceOfChildA2:                     0,
		PriceOfChildB2:                     0,
		PriceOfChildC2:                     0,
		PriceOfChildD2:                     0,
		UseOfDay3:                          0,
		RoomType3:                          "",
		NumberOfRoom3:                      0,
		RoomPrice3:                         0,
		PriceOfMale3:                       0,
		PriceOfFemale3:                     0,
		PriceOfChildA3:                     0,
		PriceOfChildB3:                     0,
		PriceOfChildC3:                     0,
		PriceOfChildD3:                     0,
		UseOfDay4:                          0,
		RoomType4:                          "",
		NumberOfRoom4:                      0,
		RoomPrice4:                         0,
		PriceOfMale4:                       0,
		PriceOfFemale4:                     0,
		PriceOfChildA4:                     0,
		PriceOfChildB4:                     0,
		PriceOfChildC4:                     0,
		PriceOfChildD4:                     0,
		UseOfDay5:                          0,
		RoomType5:                          "",
		NumberOfRoom5:                      0,
		RoomPrice5:                         0,
		PriceOfMale5:                       0,
		PriceOfFemale5:                     0,
		PriceOfChildA5:                     0,
		PriceOfChildB5:                     0,
		PriceOfChildC5:                     0,
		PriceOfChildD5:                     0,
		UseOfDay6:                          0,
		RoomType6:                          "",
		NumberOfRoom6:                      0,
		RoomPrice6:                         0,
		PriceOfMale6:                       0,
		PriceOfFemale6:                     0,
		PriceOfChildA6:                     0,
		PriceOfChildB6:                     0,
		PriceOfChildC6:                     0,
		PriceOfChildD6:                     0,
		UseOfDay7:                          0,
		RoomType7:                          "",
		NumberOfRoom7:                      0,
		RoomPrice7:                         0,
		PriceOfMale7:                       0,
		PriceOfFemale7:                     0,
		PriceOfChildA7:                     0,
		PriceOfChildB7:                     0,
		PriceOfChildC7:                     0,
		PriceOfChildD7:                     0,
		UseOfDay8:                          0,
		RoomType8:                          "",
		NumberOfRoom8:                      0,
		RoomPrice8:                         0,
		PriceOfMale8:                       0,
		PriceOfFemale8:                     0,
		PriceOfChildA8:                     0,
		PriceOfChildB8:                     0,
		PriceOfChildC8:                     0,
		PriceOfChildD8:                     0,
		UseOfDay9:                          0,
		RoomType9:                          "",
		NumberOfRoom9:                      0,
		RoomPrice9:                         0,
		PriceOfMale9:                       0,
		PriceOfFemale9:                     0,
		PriceOfChildA9:                     0,
		PriceOfChildB9:                     0,
		PriceOfChildC9:                     0,
		PriceOfChildD9:                     0,
		UseOfDay10:                         0,
		RoomType10:                         "",
		NumberOfRoom10:                     0,
		RoomPrice10:                        0,
		PriceOfMale10:                      0,
		PriceOfFemale10:                    0,
		PriceOfChildA10:                    0,
		PriceOfChildB10:                    0,
		PriceOfChildC10:                    0,
		PriceOfChildD10:                    0,
		UseOfDay11:                         0,
		RoomType11:                         "",
		NumberOfRoom11:                     0,
		RoomPrice11:                        0,
		PriceOfMale11:                      0,
		PriceOfFemale11:                    0,
		PriceOfChildA11:                    0,
		PriceOfChildB11:                    0,
		PriceOfChildC11:                    0,
		PriceOfChildD11:                    0,
		UseOfDay12:                         0,
		RoomType12:                         "",
		NumberOfRoom12:                     0,
		RoomPrice12:                        0,
		PriceOfMale12:                      0,
		PriceOfFemale12:                    0,
		PriceOfChildA12:                    0,
		PriceOfChildB12:                    0,
		PriceOfChildC12:                    0,
		PriceOfChildD12:                    0,
		OptionName1:                        "",
		OptionPrice1:                       0,
		OptionName2:                        "",
		OptionPrice2:                       0,
		NumberOfOptions2:                   0,
		OptionName3:                        "",
		OptionPrice3:                       0,
		NumberOfOptions3:                   0,
		OptionName4:                        "",
		OptionPrice4:                       0,
		NumberOfOptions4:                   0,
		OptionName5:                        "",
		OptionPrice5:                       0,
		NumberOfOptions5:                   0,
		Notes:                              "",
		LincolnSalesAgentCode:              0,
		InitSalesAgentCode:                 0,
	}

	env := &config.MysqlEnv{
		User:     "xxxx",
		Host:     "xxxx",
		Password: "xxxx",
		Port:     "xxxx",
	}
	db, err := NewDatabase(env)
	if err != nil {
		glog.Errorf("failed to create database: %v", err)
		return
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	tx, _ := db.DB.Begin()

	t.Run("test", func(t *testing.T) {
		if _, err := db.addReservationInfoToDB(&SampleReservation, tx, ctx); err != nil {
			t.Errorf("%v", err)
		}
	})
}

func TestTransactionReservationInfo(t *testing.T) {
	SampleReservation1 := scCsv.ReservationData{
		Notice:                             "予約",
		SalesAgentCode:                     "",
		SalesAgentName:                     "",
		SalesAgentShopName:                 "",
		SalesAgentShopCode:                 0,
		SalesAgentContactPerson:            "",
		SalesAgentContactEmail:             "",
		SalesAgentContactPhoneNumber:       "",
		SalesAgentContactFax:               "",
		SalesAgentPlace:                    "",
		ReservatioinNumber:                 "",
		ReservatioinDate:                   "20060102",
		NotificationNumber:                 0,
		NameKana:                           "テスト１",
		Name:                               "テスト１",
		StayDateFrom:                       "20210701",
		CheckInTime:                        "15:03",
		StayDateTo:                         "20210703",
		StayDays:                           0,
		Transportation:                     "",
		PassengerCategory:                  "",
		NumberOfRooms:                      0,
		NumberOfGuests:                     0,
		NumberOfGuestsMale:                 0,
		NumberOfGuestsFemale:               0,
		NumberOfGuestsChildA:               0,
		NumberOfGuestsChildB:               0,
		NumberOfGuestsChildC:               0,
		NumberOfGuestsChildD:               0,
		NumberOfGuide:                      0,
		ParticipationForm:                  "",
		ProductName:                        "",
		ProductCode:                        "",
		StayCondition:                      "",
		PricePerUnit:                       "",
		PriceType:                          "",
		TotalPrice:                         0,
		TotalPriceOther:                    0,
		PhoneNumber:                        "1111111",
		Email:                              "",
		PostalCode:                         "",
		HomeAddress:                        "",
		NumberOfGuestsAdult:                0,
		ReservationHolder:                  "",
		ReservationHolderKana:              "",
		ReservationHolderPhoneNumber:       "",
		ReservationHolderEmail:             "",
		ReservationHolderPostalCode:        "",
		ReservationHolderHomeAddress:       "",
		ReservationHolderCompanyName:       "",
		ReservationHolderCompanyDepartment: "",
		ReservationHolderMembershipNumber:  "",
		PointsDiscount:                     0,
		PointsAwarded:                      0,
		PointsAllocated:                    0,
		PaymentMethodName:                  "",
		UseOfDay1:                          0,
		RoomType1:                          "",
		NumberOfRoom1:                      0,
		RoomPrice1:                         0,
		PriceOfMale1:                       0,
		PriceOfFemale1:                     0,
		PriceOfChildA1:                     0,
		PriceOfChildB1:                     0,
		PriceOfChildC1:                     0,
		PriceOfChildD1:                     0,
		UseOfDay2:                          0,
		RoomType2:                          "",
		NumberOfRoom2:                      0,
		RoomPrice2:                         0,
		PriceOfMale2:                       0,
		PriceOfFemale2:                     0,
		PriceOfChildA2:                     0,
		PriceOfChildB2:                     0,
		PriceOfChildC2:                     0,
		PriceOfChildD2:                     0,
		UseOfDay3:                          0,
		RoomType3:                          "",
		NumberOfRoom3:                      0,
		RoomPrice3:                         0,
		PriceOfMale3:                       0,
		PriceOfFemale3:                     0,
		PriceOfChildA3:                     0,
		PriceOfChildB3:                     0,
		PriceOfChildC3:                     0,
		PriceOfChildD3:                     0,
		UseOfDay4:                          0,
		RoomType4:                          "",
		NumberOfRoom4:                      0,
		RoomPrice4:                         0,
		PriceOfMale4:                       0,
		PriceOfFemale4:                     0,
		PriceOfChildA4:                     0,
		PriceOfChildB4:                     0,
		PriceOfChildC4:                     0,
		PriceOfChildD4:                     0,
		UseOfDay5:                          0,
		RoomType5:                          "",
		NumberOfRoom5:                      0,
		RoomPrice5:                         0,
		PriceOfMale5:                       0,
		PriceOfFemale5:                     0,
		PriceOfChildA5:                     0,
		PriceOfChildB5:                     0,
		PriceOfChildC5:                     0,
		PriceOfChildD5:                     0,
		UseOfDay6:                          0,
		RoomType6:                          "",
		NumberOfRoom6:                      0,
		RoomPrice6:                         0,
		PriceOfMale6:                       0,
		PriceOfFemale6:                     0,
		PriceOfChildA6:                     0,
		PriceOfChildB6:                     0,
		PriceOfChildC6:                     0,
		PriceOfChildD6:                     0,
		UseOfDay7:                          0,
		RoomType7:                          "",
		NumberOfRoom7:                      0,
		RoomPrice7:                         0,
		PriceOfMale7:                       0,
		PriceOfFemale7:                     0,
		PriceOfChildA7:                     0,
		PriceOfChildB7:                     0,
		PriceOfChildC7:                     0,
		PriceOfChildD7:                     0,
		UseOfDay8:                          0,
		RoomType8:                          "",
		NumberOfRoom8:                      0,
		RoomPrice8:                         0,
		PriceOfMale8:                       0,
		PriceOfFemale8:                     0,
		PriceOfChildA8:                     0,
		PriceOfChildB8:                     0,
		PriceOfChildC8:                     0,
		PriceOfChildD8:                     0,
		UseOfDay9:                          0,
		RoomType9:                          "",
		NumberOfRoom9:                      0,
		RoomPrice9:                         0,
		PriceOfMale9:                       0,
		PriceOfFemale9:                     0,
		PriceOfChildA9:                     0,
		PriceOfChildB9:                     0,
		PriceOfChildC9:                     0,
		PriceOfChildD9:                     0,
		UseOfDay10:                         0,
		RoomType10:                         "",
		NumberOfRoom10:                     0,
		RoomPrice10:                        0,
		PriceOfMale10:                      0,
		PriceOfFemale10:                    0,
		PriceOfChildA10:                    0,
		PriceOfChildB10:                    0,
		PriceOfChildC10:                    0,
		PriceOfChildD10:                    0,
		UseOfDay11:                         0,
		RoomType11:                         "",
		NumberOfRoom11:                     0,
		RoomPrice11:                        0,
		PriceOfMale11:                      0,
		PriceOfFemale11:                    0,
		PriceOfChildA11:                    0,
		PriceOfChildB11:                    0,
		PriceOfChildC11:                    0,
		PriceOfChildD11:                    0,
		UseOfDay12:                         0,
		RoomType12:                         "",
		NumberOfRoom12:                     0,
		RoomPrice12:                        0,
		PriceOfMale12:                      0,
		PriceOfFemale12:                    0,
		PriceOfChildA12:                    0,
		PriceOfChildB12:                    0,
		PriceOfChildC12:                    0,
		PriceOfChildD12:                    0,
		OptionName1:                        "",
		OptionPrice1:                       0,
		OptionName2:                        "",
		OptionPrice2:                       0,
		NumberOfOptions2:                   0,
		OptionName3:                        "",
		OptionPrice3:                       0,
		NumberOfOptions3:                   0,
		OptionName4:                        "",
		OptionPrice4:                       0,
		NumberOfOptions4:                   0,
		OptionName5:                        "",
		OptionPrice5:                       0,
		NumberOfOptions5:                   0,
		Notes:                              "",
		LincolnSalesAgentCode:              0,
		InitSalesAgentCode:                 0,
	}
	SampleReservation2 := scCsv.ReservationData{
		Notice:                             "予約",
		SalesAgentCode:                     "",
		SalesAgentName:                     "",
		SalesAgentShopName:                 "",
		SalesAgentShopCode:                 0,
		SalesAgentContactPerson:            "",
		SalesAgentContactEmail:             "",
		SalesAgentContactPhoneNumber:       "",
		SalesAgentContactFax:               "",
		SalesAgentPlace:                    "",
		ReservatioinNumber:                 "",
		ReservatioinDate:                   "20060102",
		NotificationNumber:                 0,
		NameKana:                           "テスト２",
		Name:                               "テスト２",
		StayDateFrom:                       "20060102",
		CheckInTime:                        "15:04",
		StayDateTo:                         "20060103",
		StayDays:                           0,
		Transportation:                     "",
		PassengerCategory:                  "",
		NumberOfRooms:                      0,
		NumberOfGuests:                     0,
		NumberOfGuestsMale:                 0,
		NumberOfGuestsFemale:               0,
		NumberOfGuestsChildA:               0,
		NumberOfGuestsChildB:               0,
		NumberOfGuestsChildC:               0,
		NumberOfGuestsChildD:               0,
		NumberOfGuide:                      0,
		ParticipationForm:                  "",
		ProductName:                        "",
		ProductCode:                        "",
		StayCondition:                      "",
		PricePerUnit:                       "",
		PriceType:                          "",
		TotalPrice:                         0,
		TotalPriceOther:                    0,
		PhoneNumber:                        "2222222",
		Email:                              "",
		PostalCode:                         "",
		HomeAddress:                        "",
		NumberOfGuestsAdult:                0,
		ReservationHolder:                  "",
		ReservationHolderKana:              "",
		ReservationHolderPhoneNumber:       "",
		ReservationHolderEmail:             "",
		ReservationHolderPostalCode:        "",
		ReservationHolderHomeAddress:       "",
		ReservationHolderCompanyName:       "",
		ReservationHolderCompanyDepartment: "",
		ReservationHolderMembershipNumber:  "",
		PointsDiscount:                     0,
		PointsAwarded:                      0,
		PointsAllocated:                    0,
		PaymentMethodName:                  "",
		UseOfDay1:                          0,
		RoomType1:                          "",
		NumberOfRoom1:                      0,
		RoomPrice1:                         0,
		PriceOfMale1:                       0,
		PriceOfFemale1:                     0,
		PriceOfChildA1:                     0,
		PriceOfChildB1:                     0,
		PriceOfChildC1:                     0,
		PriceOfChildD1:                     0,
		UseOfDay2:                          0,
		RoomType2:                          "",
		NumberOfRoom2:                      0,
		RoomPrice2:                         0,
		PriceOfMale2:                       0,
		PriceOfFemale2:                     0,
		PriceOfChildA2:                     0,
		PriceOfChildB2:                     0,
		PriceOfChildC2:                     0,
		PriceOfChildD2:                     0,
		UseOfDay3:                          0,
		RoomType3:                          "",
		NumberOfRoom3:                      0,
		RoomPrice3:                         0,
		PriceOfMale3:                       0,
		PriceOfFemale3:                     0,
		PriceOfChildA3:                     0,
		PriceOfChildB3:                     0,
		PriceOfChildC3:                     0,
		PriceOfChildD3:                     0,
		UseOfDay4:                          0,
		RoomType4:                          "",
		NumberOfRoom4:                      0,
		RoomPrice4:                         0,
		PriceOfMale4:                       0,
		PriceOfFemale4:                     0,
		PriceOfChildA4:                     0,
		PriceOfChildB4:                     0,
		PriceOfChildC4:                     0,
		PriceOfChildD4:                     0,
		UseOfDay5:                          0,
		RoomType5:                          "",
		NumberOfRoom5:                      0,
		RoomPrice5:                         0,
		PriceOfMale5:                       0,
		PriceOfFemale5:                     0,
		PriceOfChildA5:                     0,
		PriceOfChildB5:                     0,
		PriceOfChildC5:                     0,
		PriceOfChildD5:                     0,
		UseOfDay6:                          0,
		RoomType6:                          "",
		NumberOfRoom6:                      0,
		RoomPrice6:                         0,
		PriceOfMale6:                       0,
		PriceOfFemale6:                     0,
		PriceOfChildA6:                     0,
		PriceOfChildB6:                     0,
		PriceOfChildC6:                     0,
		PriceOfChildD6:                     0,
		UseOfDay7:                          0,
		RoomType7:                          "",
		NumberOfRoom7:                      0,
		RoomPrice7:                         0,
		PriceOfMale7:                       0,
		PriceOfFemale7:                     0,
		PriceOfChildA7:                     0,
		PriceOfChildB7:                     0,
		PriceOfChildC7:                     0,
		PriceOfChildD7:                     0,
		UseOfDay8:                          0,
		RoomType8:                          "",
		NumberOfRoom8:                      0,
		RoomPrice8:                         0,
		PriceOfMale8:                       0,
		PriceOfFemale8:                     0,
		PriceOfChildA8:                     0,
		PriceOfChildB8:                     0,
		PriceOfChildC8:                     0,
		PriceOfChildD8:                     0,
		UseOfDay9:                          0,
		RoomType9:                          "",
		NumberOfRoom9:                      0,
		RoomPrice9:                         0,
		PriceOfMale9:                       0,
		PriceOfFemale9:                     0,
		PriceOfChildA9:                     0,
		PriceOfChildB9:                     0,
		PriceOfChildC9:                     0,
		PriceOfChildD9:                     0,
		UseOfDay10:                         0,
		RoomType10:                         "",
		NumberOfRoom10:                     0,
		RoomPrice10:                        0,
		PriceOfMale10:                      0,
		PriceOfFemale10:                    0,
		PriceOfChildA10:                    0,
		PriceOfChildB10:                    0,
		PriceOfChildC10:                    0,
		PriceOfChildD10:                    0,
		UseOfDay11:                         0,
		RoomType11:                         "",
		NumberOfRoom11:                     0,
		RoomPrice11:                        0,
		PriceOfMale11:                      0,
		PriceOfFemale11:                    0,
		PriceOfChildA11:                    0,
		PriceOfChildB11:                    0,
		PriceOfChildC11:                    0,
		PriceOfChildD11:                    0,
		UseOfDay12:                         0,
		RoomType12:                         "",
		NumberOfRoom12:                     0,
		RoomPrice12:                        0,
		PriceOfMale12:                      0,
		PriceOfFemale12:                    0,
		PriceOfChildA12:                    0,
		PriceOfChildB12:                    0,
		PriceOfChildC12:                    0,
		PriceOfChildD12:                    0,
		OptionName1:                        "",
		OptionPrice1:                       0,
		OptionName2:                        "",
		OptionPrice2:                       0,
		NumberOfOptions2:                   0,
		OptionName3:                        "",
		OptionPrice3:                       0,
		NumberOfOptions3:                   0,
		OptionName4:                        "",
		OptionPrice4:                       0,
		NumberOfOptions4:                   0,
		OptionName5:                        "",
		OptionPrice5:                       0,
		NumberOfOptions5:                   0,
		Notes:                              "",
		LincolnSalesAgentCode:              0,
		InitSalesAgentCode:                 0,
	}
	SampleReservation3 := scCsv.ReservationData{
		Notice:                             "取消",
		SalesAgentCode:                     "",
		SalesAgentName:                     "",
		SalesAgentShopName:                 "",
		SalesAgentShopCode:                 0,
		SalesAgentContactPerson:            "",
		SalesAgentContactEmail:             "",
		SalesAgentContactPhoneNumber:       "",
		SalesAgentContactFax:               "",
		SalesAgentPlace:                    "",
		ReservatioinNumber:                 "",
		ReservatioinDate:                   "20060102",
		NotificationNumber:                 0,
		NameKana:                           "テスト２",
		Name:                               "テスト２",
		StayDateFrom:                       "20060102",
		CheckInTime:                        "15:04",
		StayDateTo:                         "20060103",
		StayDays:                           0,
		Transportation:                     "",
		PassengerCategory:                  "",
		NumberOfRooms:                      0,
		NumberOfGuests:                     0,
		NumberOfGuestsMale:                 0,
		NumberOfGuestsFemale:               0,
		NumberOfGuestsChildA:               0,
		NumberOfGuestsChildB:               0,
		NumberOfGuestsChildC:               0,
		NumberOfGuestsChildD:               0,
		NumberOfGuide:                      0,
		ParticipationForm:                  "",
		ProductName:                        "",
		ProductCode:                        "",
		StayCondition:                      "",
		PricePerUnit:                       "",
		PriceType:                          "",
		TotalPrice:                         0,
		TotalPriceOther:                    0,
		PhoneNumber:                        "2222222",
		Email:                              "",
		PostalCode:                         "",
		HomeAddress:                        "",
		NumberOfGuestsAdult:                0,
		ReservationHolder:                  "",
		ReservationHolderKana:              "",
		ReservationHolderPhoneNumber:       "",
		ReservationHolderEmail:             "",
		ReservationHolderPostalCode:        "",
		ReservationHolderHomeAddress:       "",
		ReservationHolderCompanyName:       "",
		ReservationHolderCompanyDepartment: "",
		ReservationHolderMembershipNumber:  "",
		PointsDiscount:                     0,
		PointsAwarded:                      0,
		PointsAllocated:                    0,
		PaymentMethodName:                  "",
		UseOfDay1:                          0,
		RoomType1:                          "",
		NumberOfRoom1:                      0,
		RoomPrice1:                         0,
		PriceOfMale1:                       0,
		PriceOfFemale1:                     0,
		PriceOfChildA1:                     0,
		PriceOfChildB1:                     0,
		PriceOfChildC1:                     0,
		PriceOfChildD1:                     0,
		UseOfDay2:                          0,
		RoomType2:                          "",
		NumberOfRoom2:                      0,
		RoomPrice2:                         0,
		PriceOfMale2:                       0,
		PriceOfFemale2:                     0,
		PriceOfChildA2:                     0,
		PriceOfChildB2:                     0,
		PriceOfChildC2:                     0,
		PriceOfChildD2:                     0,
		UseOfDay3:                          0,
		RoomType3:                          "",
		NumberOfRoom3:                      0,
		RoomPrice3:                         0,
		PriceOfMale3:                       0,
		PriceOfFemale3:                     0,
		PriceOfChildA3:                     0,
		PriceOfChildB3:                     0,
		PriceOfChildC3:                     0,
		PriceOfChildD3:                     0,
		UseOfDay4:                          0,
		RoomType4:                          "",
		NumberOfRoom4:                      0,
		RoomPrice4:                         0,
		PriceOfMale4:                       0,
		PriceOfFemale4:                     0,
		PriceOfChildA4:                     0,
		PriceOfChildB4:                     0,
		PriceOfChildC4:                     0,
		PriceOfChildD4:                     0,
		UseOfDay5:                          0,
		RoomType5:                          "",
		NumberOfRoom5:                      0,
		RoomPrice5:                         0,
		PriceOfMale5:                       0,
		PriceOfFemale5:                     0,
		PriceOfChildA5:                     0,
		PriceOfChildB5:                     0,
		PriceOfChildC5:                     0,
		PriceOfChildD5:                     0,
		UseOfDay6:                          0,
		RoomType6:                          "",
		NumberOfRoom6:                      0,
		RoomPrice6:                         0,
		PriceOfMale6:                       0,
		PriceOfFemale6:                     0,
		PriceOfChildA6:                     0,
		PriceOfChildB6:                     0,
		PriceOfChildC6:                     0,
		PriceOfChildD6:                     0,
		UseOfDay7:                          0,
		RoomType7:                          "",
		NumberOfRoom7:                      0,
		RoomPrice7:                         0,
		PriceOfMale7:                       0,
		PriceOfFemale7:                     0,
		PriceOfChildA7:                     0,
		PriceOfChildB7:                     0,
		PriceOfChildC7:                     0,
		PriceOfChildD7:                     0,
		UseOfDay8:                          0,
		RoomType8:                          "",
		NumberOfRoom8:                      0,
		RoomPrice8:                         0,
		PriceOfMale8:                       0,
		PriceOfFemale8:                     0,
		PriceOfChildA8:                     0,
		PriceOfChildB8:                     0,
		PriceOfChildC8:                     0,
		PriceOfChildD8:                     0,
		UseOfDay9:                          0,
		RoomType9:                          "",
		NumberOfRoom9:                      0,
		RoomPrice9:                         0,
		PriceOfMale9:                       0,
		PriceOfFemale9:                     0,
		PriceOfChildA9:                     0,
		PriceOfChildB9:                     0,
		PriceOfChildC9:                     0,
		PriceOfChildD9:                     0,
		UseOfDay10:                         0,
		RoomType10:                         "",
		NumberOfRoom10:                     0,
		RoomPrice10:                        0,
		PriceOfMale10:                      0,
		PriceOfFemale10:                    0,
		PriceOfChildA10:                    0,
		PriceOfChildB10:                    0,
		PriceOfChildC10:                    0,
		PriceOfChildD10:                    0,
		UseOfDay11:                         0,
		RoomType11:                         "",
		NumberOfRoom11:                     0,
		RoomPrice11:                        0,
		PriceOfMale11:                      0,
		PriceOfFemale11:                    0,
		PriceOfChildA11:                    0,
		PriceOfChildB11:                    0,
		PriceOfChildC11:                    0,
		PriceOfChildD11:                    0,
		UseOfDay12:                         0,
		RoomType12:                         "",
		NumberOfRoom12:                     0,
		RoomPrice12:                        0,
		PriceOfMale12:                      0,
		PriceOfFemale12:                    0,
		PriceOfChildA12:                    0,
		PriceOfChildB12:                    0,
		PriceOfChildC12:                    0,
		PriceOfChildD12:                    0,
		OptionName1:                        "",
		OptionPrice1:                       0,
		OptionName2:                        "",
		OptionPrice2:                       0,
		NumberOfOptions2:                   0,
		OptionName3:                        "",
		OptionPrice3:                       0,
		NumberOfOptions3:                   0,
		OptionName4:                        "",
		OptionPrice4:                       0,
		NumberOfOptions4:                   0,
		OptionName5:                        "",
		OptionPrice5:                       0,
		NumberOfOptions5:                   0,
		Notes:                              "",
		LincolnSalesAgentCode:              0,
		InitSalesAgentCode:                 0,
	}

	SampleReservations := []*scCsv.ReservationData{
		&SampleReservation1,
		&SampleReservation2,
		&SampleReservation3,
	}

	env := &config.MysqlEnv{
		User:     "xxxx",
		Host:     "xxxx",
		Password: "xxxx",
		Port:     "xxxx",
	}
	db, err := NewDatabase(env)
	if err != nil {
		t.Errorf("failed to create database: %v", err)
		return
	}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	t.Run("test", func(t *testing.T) {
		errors, err := db.TransactionReservationInfo(SampleReservations, ctx)
		if err != nil {
			t.Errorf("failed to process transaction: %v", err)
		}

		if len(errors) != 0 {
			for i, err := range errors {
				t.Errorf("%dth row error: %v", i, err)
			}
		}
	})
}

func TestTransaction(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	env := &config.MysqlEnv{
		User:     "xxxx",
		Host:     "xxxx",
		Password: "xxxx",
		Port:     "xxxx",
	}
	db, err := NewDatabase(env)
	if err != nil {
		t.Errorf("failed to create database: %v", err)
		return
	}
	var id int

	SampleReservationError1 := []*scCsv.ReservationData{
		{
			Notice:                             "予約",
			SalesAgentCode:                     "",
			SalesAgentName:                     "",
			SalesAgentShopName:                 "テストトラベル",
			SalesAgentShopCode:                 0,
			SalesAgentContactPerson:            "",
			SalesAgentContactEmail:             "",
			SalesAgentContactPhoneNumber:       "",
			SalesAgentContactFax:               "",
			SalesAgentPlace:                    "",
			ReservatioinNumber:                 "",
			ReservatioinDate:                   "20060102",
			NotificationNumber:                 0,
			NameKana:                           "テスト１",
			Name:                               "テスト１",
			StayDateFrom:                       "20210701",
			CheckInTime:                        "15:03",
			StayDateTo:                         "20210703",
			StayDays:                           2,
			Transportation:                     "",
			PassengerCategory:                  "",
			NumberOfRooms:                      1,
			NumberOfGuests:                     3,
			NumberOfGuestsMale:                 1,
			NumberOfGuestsFemale:               1,
			NumberOfGuestsChildA:               1,
			NumberOfGuestsChildB:               0,
			NumberOfGuestsChildC:               0,
			NumberOfGuestsChildD:               0,
			NumberOfGuide:                      0,
			ParticipationForm:                  "",
			ProductName:                        "テストプラン１",
			ProductCode:                        "",
			StayCondition:                      "",
			PricePerUnit:                       "",
			PriceType:                          "",
			TotalPrice:                         0,
			TotalPriceOther:                    0,
			PhoneNumber:                        "1111111",
			Email:                              "",
			PostalCode:                         "111-2222",
			HomeAddress:                        "テスト都テスト区テスト111",
			NumberOfGuestsAdult:                0,
			ReservationHolder:                  "テスト１",
			ReservationHolderKana:              "テスト１",
			ReservationHolderPhoneNumber:       "00011112222",
			ReservationHolderEmail:             "",
			ReservationHolderPostalCode:        "111-2222",
			ReservationHolderHomeAddress:       "テスト都テスト区テスト111",
			ReservationHolderCompanyName:       "",
			ReservationHolderCompanyDepartment: "",
			ReservationHolderMembershipNumber:  "",
			PointsDiscount:                     0,
			PointsAwarded:                      0,
			PointsAllocated:                    0,
			PaymentMethodName:                  "",
			UseOfDay1:                          0,
			RoomType1:                          "",
			NumberOfRoom1:                      0,
			RoomPrice1:                         0,
			PriceOfMale1:                       0,
			PriceOfFemale1:                     0,
			PriceOfChildA1:                     0,
			PriceOfChildB1:                     0,
			PriceOfChildC1:                     0,
			PriceOfChildD1:                     0,
			UseOfDay2:                          0,
			RoomType2:                          "",
			NumberOfRoom2:                      0,
			RoomPrice2:                         0,
			PriceOfMale2:                       0,
			PriceOfFemale2:                     0,
			PriceOfChildA2:                     0,
			PriceOfChildB2:                     0,
			PriceOfChildC2:                     0,
			PriceOfChildD2:                     0,
			UseOfDay3:                          0,
			RoomType3:                          "",
			NumberOfRoom3:                      0,
			RoomPrice3:                         0,
			PriceOfMale3:                       0,
			PriceOfFemale3:                     0,
			PriceOfChildA3:                     0,
			PriceOfChildB3:                     0,
			PriceOfChildC3:                     0,
			PriceOfChildD3:                     0,
			UseOfDay4:                          0,
			RoomType4:                          "",
			NumberOfRoom4:                      0,
			RoomPrice4:                         0,
			PriceOfMale4:                       0,
			PriceOfFemale4:                     0,
			PriceOfChildA4:                     0,
			PriceOfChildB4:                     0,
			PriceOfChildC4:                     0,
			PriceOfChildD4:                     0,
			UseOfDay5:                          0,
			RoomType5:                          "",
			NumberOfRoom5:                      0,
			RoomPrice5:                         0,
			PriceOfMale5:                       0,
			PriceOfFemale5:                     0,
			PriceOfChildA5:                     0,
			PriceOfChildB5:                     0,
			PriceOfChildC5:                     0,
			PriceOfChildD5:                     0,
			UseOfDay6:                          0,
			RoomType6:                          "",
			NumberOfRoom6:                      0,
			RoomPrice6:                         0,
			PriceOfMale6:                       0,
			PriceOfFemale6:                     0,
			PriceOfChildA6:                     0,
			PriceOfChildB6:                     0,
			PriceOfChildC6:                     0,
			PriceOfChildD6:                     0,
			UseOfDay7:                          0,
			RoomType7:                          "",
			NumberOfRoom7:                      0,
			RoomPrice7:                         0,
			PriceOfMale7:                       0,
			PriceOfFemale7:                     0,
			PriceOfChildA7:                     0,
			PriceOfChildB7:                     0,
			PriceOfChildC7:                     0,
			PriceOfChildD7:                     0,
			UseOfDay8:                          0,
			RoomType8:                          "",
			NumberOfRoom8:                      0,
			RoomPrice8:                         0,
			PriceOfMale8:                       0,
			PriceOfFemale8:                     0,
			PriceOfChildA8:                     0,
			PriceOfChildB8:                     0,
			PriceOfChildC8:                     0,
			PriceOfChildD8:                     0,
			UseOfDay9:                          0,
			RoomType9:                          "",
			NumberOfRoom9:                      0,
			RoomPrice9:                         0,
			PriceOfMale9:                       0,
			PriceOfFemale9:                     0,
			PriceOfChildA9:                     0,
			PriceOfChildB9:                     0,
			PriceOfChildC9:                     0,
			PriceOfChildD9:                     0,
			UseOfDay10:                         0,
			RoomType10:                         "",
			NumberOfRoom10:                     0,
			RoomPrice10:                        0,
			PriceOfMale10:                      0,
			PriceOfFemale10:                    0,
			PriceOfChildA10:                    0,
			PriceOfChildB10:                    0,
			PriceOfChildC10:                    0,
			PriceOfChildD10:                    0,
			UseOfDay11:                         0,
			RoomType11:                         "",
			NumberOfRoom11:                     0,
			RoomPrice11:                        0,
			PriceOfMale11:                      0,
			PriceOfFemale11:                    0,
			PriceOfChildA11:                    0,
			PriceOfChildB11:                    0,
			PriceOfChildC11:                    0,
			PriceOfChildD11:                    0,
			UseOfDay12:                         0,
			RoomType12:                         "",
			NumberOfRoom12:                     0,
			RoomPrice12:                        0,
			PriceOfMale12:                      0,
			PriceOfFemale12:                    0,
			PriceOfChildA12:                    0,
			PriceOfChildB12:                    0,
			PriceOfChildC12:                    0,
			PriceOfChildD12:                    0,
			OptionName1:                        "",
			OptionPrice1:                       0,
			OptionName2:                        "",
			OptionPrice2:                       0,
			NumberOfOptions2:                   0,
			OptionName3:                        "",
			OptionPrice3:                       0,
			NumberOfOptions3:                   0,
			OptionName4:                        "",
			OptionPrice4:                       0,
			NumberOfOptions4:                   0,
			OptionName5:                        "",
			OptionPrice5:                       0,
			NumberOfOptions5:                   0,
			Notes:                              "",
			LincolnSalesAgentCode:              0,
			InitSalesAgentCode:                 0,
		},
		{
			Notice:                             "取消",
			SalesAgentCode:                     "",
			SalesAgentName:                     "",
			SalesAgentShopName:                 "テストトラベル",
			SalesAgentShopCode:                 0,
			SalesAgentContactPerson:            "",
			SalesAgentContactEmail:             "",
			SalesAgentContactPhoneNumber:       "",
			SalesAgentContactFax:               "",
			SalesAgentPlace:                    "",
			ReservatioinNumber:                 "",
			ReservatioinDate:                   "20060102",
			NotificationNumber:                 0,
			NameKana:                           "テスト２",
			Name:                               "テスト２",
			StayDateFrom:                       "20210701",
			CheckInTime:                        "15:03",
			StayDateTo:                         "20210703",
			StayDays:                           2,
			Transportation:                     "",
			PassengerCategory:                  "",
			NumberOfRooms:                      1,
			NumberOfGuests:                     3,
			NumberOfGuestsMale:                 1,
			NumberOfGuestsFemale:               1,
			NumberOfGuestsChildA:               1,
			NumberOfGuestsChildB:               0,
			NumberOfGuestsChildC:               0,
			NumberOfGuestsChildD:               0,
			NumberOfGuide:                      0,
			ParticipationForm:                  "",
			ProductName:                        "テストプラン２",
			ProductCode:                        "",
			StayCondition:                      "",
			PricePerUnit:                       "",
			PriceType:                          "",
			TotalPrice:                         0,
			TotalPriceOther:                    0,
			PhoneNumber:                        "2222222222222",
			Email:                              "",
			PostalCode:                         "111-2222",
			HomeAddress:                        "テスト都テスト区テスト111",
			NumberOfGuestsAdult:                0,
			ReservationHolder:                  "テスト２",
			ReservationHolderKana:              "テスト２",
			ReservationHolderPhoneNumber:       "00011112222",
			ReservationHolderEmail:             "",
			ReservationHolderPostalCode:        "111-2222",
			ReservationHolderHomeAddress:       "テスト都テスト区テスト111",
			ReservationHolderCompanyName:       "",
			ReservationHolderCompanyDepartment: "",
			ReservationHolderMembershipNumber:  "",
			PointsDiscount:                     0,
			PointsAwarded:                      0,
			PointsAllocated:                    0,
			PaymentMethodName:                  "",
			UseOfDay1:                          0,
			RoomType1:                          "",
			NumberOfRoom1:                      0,
			RoomPrice1:                         0,
			PriceOfMale1:                       0,
			PriceOfFemale1:                     0,
			PriceOfChildA1:                     0,
			PriceOfChildB1:                     0,
			PriceOfChildC1:                     0,
			PriceOfChildD1:                     0,
			UseOfDay2:                          0,
			RoomType2:                          "",
			NumberOfRoom2:                      0,
			RoomPrice2:                         0,
			PriceOfMale2:                       0,
			PriceOfFemale2:                     0,
			PriceOfChildA2:                     0,
			PriceOfChildB2:                     0,
			PriceOfChildC2:                     0,
			PriceOfChildD2:                     0,
			UseOfDay3:                          0,
			RoomType3:                          "",
			NumberOfRoom3:                      0,
			RoomPrice3:                         0,
			PriceOfMale3:                       0,
			PriceOfFemale3:                     0,
			PriceOfChildA3:                     0,
			PriceOfChildB3:                     0,
			PriceOfChildC3:                     0,
			PriceOfChildD3:                     0,
			UseOfDay4:                          0,
			RoomType4:                          "",
			NumberOfRoom4:                      0,
			RoomPrice4:                         0,
			PriceOfMale4:                       0,
			PriceOfFemale4:                     0,
			PriceOfChildA4:                     0,
			PriceOfChildB4:                     0,
			PriceOfChildC4:                     0,
			PriceOfChildD4:                     0,
			UseOfDay5:                          0,
			RoomType5:                          "",
			NumberOfRoom5:                      0,
			RoomPrice5:                         0,
			PriceOfMale5:                       0,
			PriceOfFemale5:                     0,
			PriceOfChildA5:                     0,
			PriceOfChildB5:                     0,
			PriceOfChildC5:                     0,
			PriceOfChildD5:                     0,
			UseOfDay6:                          0,
			RoomType6:                          "",
			NumberOfRoom6:                      0,
			RoomPrice6:                         0,
			PriceOfMale6:                       0,
			PriceOfFemale6:                     0,
			PriceOfChildA6:                     0,
			PriceOfChildB6:                     0,
			PriceOfChildC6:                     0,
			PriceOfChildD6:                     0,
			UseOfDay7:                          0,
			RoomType7:                          "",
			NumberOfRoom7:                      0,
			RoomPrice7:                         0,
			PriceOfMale7:                       0,
			PriceOfFemale7:                     0,
			PriceOfChildA7:                     0,
			PriceOfChildB7:                     0,
			PriceOfChildC7:                     0,
			PriceOfChildD7:                     0,
			UseOfDay8:                          0,
			RoomType8:                          "",
			NumberOfRoom8:                      0,
			RoomPrice8:                         0,
			PriceOfMale8:                       0,
			PriceOfFemale8:                     0,
			PriceOfChildA8:                     0,
			PriceOfChildB8:                     0,
			PriceOfChildC8:                     0,
			PriceOfChildD8:                     0,
			UseOfDay9:                          0,
			RoomType9:                          "",
			NumberOfRoom9:                      0,
			RoomPrice9:                         0,
			PriceOfMale9:                       0,
			PriceOfFemale9:                     0,
			PriceOfChildA9:                     0,
			PriceOfChildB9:                     0,
			PriceOfChildC9:                     0,
			PriceOfChildD9:                     0,
			UseOfDay10:                         0,
			RoomType10:                         "",
			NumberOfRoom10:                     0,
			RoomPrice10:                        0,
			PriceOfMale10:                      0,
			PriceOfFemale10:                    0,
			PriceOfChildA10:                    0,
			PriceOfChildB10:                    0,
			PriceOfChildC10:                    0,
			PriceOfChildD10:                    0,
			UseOfDay11:                         0,
			RoomType11:                         "",
			NumberOfRoom11:                     0,
			RoomPrice11:                        0,
			PriceOfMale11:                      0,
			PriceOfFemale11:                    0,
			PriceOfChildA11:                    0,
			PriceOfChildB11:                    0,
			PriceOfChildC11:                    0,
			PriceOfChildD11:                    0,
			UseOfDay12:                         0,
			RoomType12:                         "",
			NumberOfRoom12:                     0,
			RoomPrice12:                        0,
			PriceOfMale12:                      0,
			PriceOfFemale12:                    0,
			PriceOfChildA12:                    0,
			PriceOfChildB12:                    0,
			PriceOfChildC12:                    0,
			PriceOfChildD12:                    0,
			OptionName1:                        "",
			OptionPrice1:                       0,
			OptionName2:                        "",
			OptionPrice2:                       0,
			NumberOfOptions2:                   0,
			OptionName3:                        "",
			OptionPrice3:                       0,
			NumberOfOptions3:                   0,
			OptionName4:                        "",
			OptionPrice4:                       0,
			NumberOfOptions4:                   0,
			OptionName5:                        "",
			OptionPrice5:                       0,
			NumberOfOptions5:                   0,
			Notes:                              "",
			LincolnSalesAgentCode:              0,
			InitSalesAgentCode:                 0,
		},
	}

	tests := []struct {
		name            string
		reservationData []*scCsv.ReservationData
	}{
		{
			name:            "正常系",
			reservationData: SampleReservationError1,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			model, err := db.CreateCsvUploadTransaction(ctx, "test.csv", time.Now(), "", "")
			if err != nil {
				t.Errorf("failed to insert record to database: %v", err)
			}

			// トランザクション：insertReservation, insertGuest
			errors, err := db.TransactionReservationInfo(tt.reservationData, ctx)

			// トランザクションOK...csvステータスをcompleteに変える
			if err == nil && errors == nil {
				if err := db.finishCsvUpload(model.ID, ctx); err != nil {
					t.Errorf("failed to upload csv_upload_transaction status: %v", err)
				} else {
					sugar.Info("successful of csv uploading")
				}
			} else {
				// トランザクションERROR...csvステータスをerrorに変える
				if err := db.updateCsvUploadTransactionStatusToError(id, ctx); err != nil {
					t.Errorf("failed to upload csv_upload_transaction status: %v", err)
				} else {
					sugar.Info("failed to upload csv")
				}
				// csv_execution_errorにerror内容を入れる
				// TODO 戻り値のidsをチャネル使ってwebsocketに渡す
				ids := db.InsertCSVExecutionError(ctx, errors, id)
				sugar.Infof("error ids: %v", ids)
			}
		})
	}
}

func TestSelectErrorCSVRows(t *testing.T) {

	env := &config.MysqlEnv{
		User:     "xxxx",
		Host:     "xxxx",
		Password: "xxxx",
		Port:     "xxxx",
	}
	db, err := NewDatabase(env)
	if err != nil {
		glog.Errorf("failed to create database: %v", err)
		return
	}

	// error_csvを取得
	//csvIds := []int{1, 2}

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	//tx, _ := db.DB.Begin()
	// tx.Exec("Insert into csv_upload_transaction (status, created_time_in_windows, file_name) values ('error', '2021-07-19 03:17:24', 'リンカーン_CSV_異常系.csv');")
	// tx.Commit()
	// rows, err := tx.Query("select * from csv_upload_transaction;")
	// fmt.Printf("%+v", rows)
	// tx.Exec("Insert into csv_execution_errors (line_number, customer_name, customer_phone_number, error_message, status, csv_id) values (2, '異常系テスト２', '9076758298', 'error', 0, 1);")
	// tx.Commit()
	//tx, _ = db.DB.Begin()
	t.Run("test", func(t *testing.T) {
		rows, err := db.GetCsvExecutionErrorsWithCsvUploadTransactionByStatus(ctx, 0)
		if err != nil {
			t.Errorf("%v", err)
		}
		fmt.Printf("%v", rows)
	})
}
