ui-backend-for-omotebako-site-controller:
    scale: 1
    startup: yes
    always: yes
    network: NodePort
    ports:
      - name: site-controller
        protocol: TCP
        port: 8080
        nodePort: 30110
    env:
      KANBAN_ADDR: aion-statuskanban:10000
      MYSQL_USER: XXXXX
      MYSQL_HOST: XXXXX
      MYSQL_PASSWORD: XXXXXXXX
      MYSQL_PORT: 3306
      POLLING_INTERVAL: 1
      MOUNT_PATH: /mnt/windows
      PORT: 8080
    nextService:
      sc_csv:
        - name: omotebako-sc
    volumeMountPathList:
      - /mnt/windows:/mnt/windows/192.168.XXX.XX/Sample_SC
